#日志信息
app:
  name: bon-base
  logPath: C:/logs
  logLevel: INFO

#web端口
server:
    port: 3020

spring:
# jackson时间格式化
  jackson:
    time-zone: GMT+8
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/wxmanage?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&&zeroDateTimeBehavior=convertToNull
      name: wxmanage
      username: root
      password: root
      initialSize: 5    # 初始化大小
      minIdle: 5        # 最小
      maxActive: 20     # 最大
      maxWait: 60000    # 获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true                    # 打开PSCache
      maxPoolPreparedStatementPerConnectionSize: 20   # 指定每个连接上PSCache的大小
      filters: stat,wall,log4j                        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

## Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true
  auto-runtime-dialect: true
