package com.bon.domain.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.io.Serializable;
import java.util.Date;

/**
 * 
 * 实体类对应的数据表为：  sys_base
 * @author null
 * @date 2018-07-12 11:39:50
 */
@ApiModel(value ="SysBase")
public class SysBase implements Serializable {
    @Id
    @GeneratedValue(generator = "JDBC")
    @ApiModelProperty(value = "ID")
    private Long sysBaseId;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date gmtCreate;

    @ApiModelProperty(value = "最后一次更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date gmtModified;

    @ApiModelProperty(value = "表名")
    private String tableName;

    @ApiModelProperty(value = "表备注")
    private String tableRemark;

    @ApiModelProperty(value = "字段名")
    private String filedName;

    @ApiModelProperty(value = "字段类型")
    private String filedType;

    @ApiModelProperty(value = "字段长度")
    private Integer filedLength;

    @ApiModelProperty(value = "00:是，01：否；是否可以为空")
    private String isNull;

    @ApiModelProperty(value = "00:是，01：否；是否唯一")
    private String isUnique;

    @ApiModelProperty(value = "默认值")
    private String defaultValue;

    @ApiModelProperty(value = "字段备注")
    private String filedRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_base
     *
     * @mbg.generated 2018-07-12 11:39:50
     */
    private static final long serialVersionUID = 1L;

    public SysBase(Long sysBaseId, Date gmtCreate, Date gmtModified, String tableName, String tableRemark, String filedName, String filedType, Integer filedLength, String isNull, String isUnique, String defaultValue, String filedRemark) {
        this.sysBaseId = sysBaseId;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.tableName = tableName;
        this.tableRemark = tableRemark;
        this.filedName = filedName;
        this.filedType = filedType;
        this.filedLength = filedLength;
        this.isNull = isNull;
        this.isUnique = isUnique;
        this.defaultValue = defaultValue;
        this.filedRemark = filedRemark;
    }

    public SysBase() {
        super();
    }

    public Long getSysBaseId() {
        return sysBaseId;
    }

    public void setSysBaseId(Long sysBaseId) {
        this.sysBaseId = sysBaseId;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    public String getTableRemark() {
        return tableRemark;
    }

    public void setTableRemark(String tableRemark) {
        this.tableRemark = tableRemark == null ? null : tableRemark.trim();
    }

    public String getFiledName() {
        return filedName;
    }

    public void setFiledName(String filedName) {
        this.filedName = filedName == null ? null : filedName.trim();
    }

    public String getFiledType() {
        return filedType;
    }

    public void setFiledType(String filedType) {
        this.filedType = filedType == null ? null : filedType.trim();
    }

    public Integer getFiledLength() {
        return filedLength;
    }

    public void setFiledLength(Integer filedLength) {
        this.filedLength = filedLength;
    }

    public String getIsNull() {
        return isNull;
    }

    public void setIsNull(String isNull) {
        this.isNull = isNull == null ? null : isNull.trim();
    }

    public String getIsUnique() {
        return isUnique;
    }

    public void setIsUnique(String isUnique) {
        this.isUnique = isUnique == null ? null : isUnique.trim();
    }

    public String getDefaultValue() {
        return defaultValue;
    }

    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue == null ? null : defaultValue.trim();
    }

    public String getFiledRemark() {
        return filedRemark;
    }

    public void setFiledRemark(String filedRemark) {
        this.filedRemark = filedRemark == null ? null : filedRemark.trim();
    }
}